import {RELEASE,esc,safeUrl,koreanTime,openPage,closePage,visiblePages,buildRecord,recordFingerprint,validateData} from './research-core.mjs';
import {connectRecords} from './research-records.mjs';
const $=s=>document.querySelector(s),root=$('#workspace'),nav=$('#page-nav');
const key='invest.research.cpi.workspace.v1';
let cached={};try{cached=JSON.parse(localStorage.getItem(key)||'{}');}catch{}
const uuid=()=>crypto.randomUUID();
const blank=()=>({id:uuid(),title:'CPI 분석',oneLiner:'',body:'',evidence:[],expected:null,dirty:false,operation:null});
let state={pages:['summary','cpi'],active:'cpi',full:null,series:'all',month:6,view:'card',...cached.layout};
if(!Array.isArray(state.pages)||!state.pages.length||state.pages.length>3)state.pages=['summary','cpi'];
let draft=cached.draft&&typeof cached.draft.body==='string'?cached.draft:blank();
let highlights=Array.isArray(cached.highlights)?cached.highlights:[],records=[],data,repo,unwatch,busy=false,conflict=false,saveStatus='',cloudStatus='기록보관실 연결 중',localError=false;
const scrolls=new Map();
let focusReturn=null;
function expand(id){if(!state.full)focusReturn={pages:[...state.pages],active:state.active,scrolls:new Map(scrolls)};state={...state,full:id,active:id};render();}
function restore(){if(focusReturn){state={...state,pages:focusReturn.pages,active:focusReturn.active,full:null};scrolls.clear();focusReturn.scrolls.forEach((v,k)=>scrolls.set(k,v));focusReturn=null;root.innerHTML="";}else state.full=null;render();}
function persist(){try{localStorage.setItem(key,JSON.stringify({layout:state,draft,highlights}));localError=false;}catch{localError=true;$('#notice').textContent='이 브라우저에 초안을 보관하지 못했습니다. 창을 닫기 전에 초안을 내려받으세요.';}}
function notice(text){$('#notice').textContent=text||`${cloudStatus}${localError?' · 초안 보관 실패':''}`;}
function link(url,label){const u=safeUrl(url);return u?`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:'';}
const title=id=>({summary:'핵심 정리',cpi:'변화와 비교',release:'세부 근거',note:'내 분석',collection:'관련 자료 모음'}[id]||records.find(r=>'record:'+r.id===id)?.title||'기록');
function spark(series='all'){const a=data.points.map(x=>x[series]),lo=Math.min(...a),hi=Math.max(...a),d=hi-lo||1;return `<svg class="spark" viewBox="0 0 200 32" preserveAspectRatio="none" role="img" aria-label="${esc(data.series[series].title)} 월간 상승률 흐름"><polyline fill="none" stroke="var(--green)" stroke-width="2" points="${a.map((v,i)=>`${4+i*192/(a.length-1)},${28-(v-lo)/d*24}`).join(' ')}"/></svg>`;}
function sourceRows(list){return list.map(r=>`<button class="tile" data-open="record:${esc(r.id)}"><span class="tag">${r.kind==='idea'?'분석':r.kind==='news'?'뉴스':'기록'}</span><strong>${esc(r.title)}</strong><span class="muted">${esc(r.channel||'기록보관실')} · ${esc(r.date||'날짜 없음')}</span><p>${esc(r.oneLiner||'')}</p></button>`).join('');}
function summary(){const s=data.series.all;return `<span class="muted">01 / 먼저 볼 핵심</span><h1>미국 물가</h1><span class="tag">${esc(data.period)} 확인본</span><div class="hero"><h2>전체 CPI</h2><div class="value">${s.yoy.toFixed(1)}%</div><p>전년 대비 · 비계절조정<br>이전 ${s.previousYoy.toFixed(1)}%</p><p>전월 대비 ${s.previousMom.toFixed(1)}% → ${s.mom.toFixed(1)}%<br>계절조정</p>${spark()}</div><button class="primary" data-open="cpi">변화와 비교 →</button><h2>골라 담은 핵심</h2>${highlights.length?highlights.map(id=>data.evidence.find(e=>e.id===id)).filter(Boolean).map(e=>`<div class="evidence"><span class="tag">공식 사실 · 직접 선택</span><p>${esc(e.text)}</p><div class="row"><button data-open="release">근거 열기 →</button><button data-unpin="${esc(e.id)}">빼기</button></div>${link(data.sourceUrl,'BLS 출처')}</div>`).join(''):'<p class="empty">오른쪽 근거에서 핵심에 담을 내용을 선택하세요.</p>'}<h2>공식 발표·관련 뉴스</h2><button class="tile" data-open="release"><strong>${esc(data.period)} CPI 공식 발표</strong><span>BLS · ${koreanTime(data.publishedAt)} 서울</span></button>${sourceRows(records.filter(r=>r.kind==='news').slice(0,2))}<p class="muted">관련 뉴스는 기록보관실에서 CPI 주제로 연결한 자료입니다.</p><button data-open="collection">연결된 자료 모두 보기 →</button><h2>내 분석</h2>${sourceRows(records.filter(r=>r.kind==='idea').slice(0,2))}<button data-open="note">${draft.dirty?'작성 중인 분석 이어쓰기':'분석 작성'} →</button><h2>다음 확인</h2><p>${koreanTime(data.nextReleaseAt)} 서울</p><p>${link(data.scheduleUrl,'공식 발표 일정')}</p>${Date.now()>Date.parse(data.nextReleaseAt)?'<p class="warning">확인본의 예정일이 지났습니다. 새 발표는 공식 원문에서 확인하세요.</p>':''}`;}
function cpi(){const s=data.series[state.series];const month=data.points[Math.min(state.month,data.points.length-1)];return `<span class="muted">02 / 함께 볼 변화</span><h1>${esc(s.title)}</h1><span>${esc(data.period)} · 미국 도시 소비자</span><div class="hero"><span>전년 대비 · 비계절조정</span><div class="value">${s.yoy.toFixed(1)}%</div><p>이전 ${s.previousYoy.toFixed(1)}% → 최근 ${s.yoy.toFixed(1)}%</p></div><div class="facts"><div><span>전월 대비 · 계절조정</span><b>${s.mom.toFixed(1)}%</b></div><div><span>이전 전월 대비</span><b>${s.previousMom.toFixed(1)}%</b></div><div><span>실제 발표 · 서울</span><b>${koreanTime(data.publishedAt)}</b></div><div><span>다음 발표 · 서울</span><b>${koreanTime(data.nextReleaseAt)}</b></div></div><div class="row"><button data-series="all" aria-pressed="${state.series==='all'}">전체 CPI</button><button data-series="core" aria-pressed="${state.series==='core'}">근원 CPI</button></div><h2>월별 상승률 흐름</h2><p>전월 대비 · 계절조정 · %</p><div class="chart"></div><label>확인할 기준기간 <select id="month">${data.points.map((p,i)=>`<option value="${i}" ${i===state.month?'selected':''}>${esc(p.period)}</option>`).join('')}</select> <b>${month[state.series].toFixed(1)}%</b></label><p class="muted">BLS 발표표 A · ${data.points[0].period}~${data.points.at(-1).period}<br>공식 중립선 미확인 · 기준선 표시 없음</p><details data-detail="values"><summary>월별 원자료</summary><table><thead><tr><th>기간</th><th>전체 %</th><th>근원 %</th></tr></thead><tbody>${data.points.map(p=>`<tr><td>${p.period}</td><td>${p.all.toFixed(1)}</td><td>${p.core.toFixed(1)}</td></tr>`).join('')}</tbody></table></details><div class="row"><button class="primary" data-open="release">공식 발표문 오른쪽에 열기 →</button><button data-open="note">내 분석 →</button></div><p>${link(data.sourceUrl,'원자료')} · ${link(data.scheduleUrl,'공식 일정')}</p><p class="muted">미국 원시각: ${esc(data.publishedAt)}<br>${esc(data.releaseTimezone)}</p>`;}
function release(){return `<span class="muted">03 / 더 확인할 근거</span><h1>월간 상승의<br>세부 요인</h1><p>BLS · ${koreanTime(data.publishedAt)} 서울<br>${esc(data.period)} 발표 한국어 요약</p>${data.evidence.map(e=>`<section class="source"><h2>${esc(e.label)}</h2><p>${esc(e.text)}</p><button data-pin="${esc(e.id)}" aria-pressed="${highlights.includes(e.id)}">${highlights.includes(e.id)?'핵심에 담김':'← 핵심에 담기'}</button></section>`).join('')}<p>${link(data.sourceUrl,'BLS 원문')}</p><button class="primary" data-open="note">연결한 근거로 분석 작성 →</button><p class="muted">공식 사실 요약입니다. 투자 판단은 개인 분석에 별도로 기록합니다.</p>`;}
function note(){return `<span class="muted">개인 기록 / 사실과 판단 구분</span><h1>내 분석</h1><label>제목<input id="draft-title" type="text" maxlength="160" value="${esc(draft.title)}"></label><label>핵심 한 줄<input id="draft-one" type="text" maxlength="300" value="${esc(draft.oneLiner)}"></label><label>내 해석과 확인할 점<textarea id="draft-body" maxlength="20000" placeholder="공식 사실을 어떻게 해석하는지, 무엇을 더 확인할지 기록하세요.">${esc(draft.body)}</textarea></label><h2>채택한 공식 근거</h2>${data.evidence.map(e=>`<label><input type="checkbox" data-evidence="${esc(e.id)}" ${draft.evidence.includes(e.id)?'checked':''}>${esc(e.label)}</label>`).join('')}<div class="row"><button class="primary" data-action="save" ${busy||!repo?'disabled':''}>${busy?'저장 확인 중…':'기록보관실에 저장'}</button><button data-action="export">초안 내려받기</button><button data-action="new">새 분석</button></div><div class="save-status" role="status">${esc(saveStatus|| (draft.dirty?'이 브라우저에 초안 보관 중':'저장하면 기존 기록보관실에서도 확인할 수 있습니다.'))}</div>${conflict?'<p class="warning">다른 화면에서 기록이 변경됐습니다. 현재 초안은 보존했습니다.</p><button data-action="copy">현재 초안을 새 기록으로 저장</button>':''}<p class="muted">${esc(cloudStatus)}<br>저장 전 초안은 이 브라우저에만 보관됩니다.</p>${draft.expected?`<p><a href="research-cpi.html?record=${encodeURIComponent(draft.id)}" target="_blank" rel="noopener">이 분석의 고유 주소 ↗</a></p>`:''}`;}
function collection(){return `<h1>CPI 관련 자료</h1><p>기록보관실에서 CPI 주제로 연결한 기록</p><div class="row"><button data-view="card" aria-pressed="${state.view==='card'}">카드</button><button data-view="table" aria-pressed="${state.view==='table'}">표</button><a href="records.html" target="_blank" rel="noopener">기존 8개 보기 ↗</a></div>${!records.length?'<p class="empty">연결된 기록이 없습니다. 저장한 CPI 분석이 여기에 나타납니다.</p>':state.view==='table'?`<table><thead><tr><th>자료</th><th>날짜</th></tr></thead><tbody>${records.map(r=>`<tr><td><button data-open="record:${esc(r.id)}">${esc(r.title)}</button></td><td>${esc(r.date)}</td></tr>`).join('')}</tbody></table>`:sourceRows(records)}`;}
function recordPage(id){const r=records.find(x=>'record:'+x.id===id);if(!r)return '<h1>기록 확인 중</h1><p>연결을 확인하거나 기록보관실에서 찾아보세요.</p>';return `<span class="tag">${esc(r.kind==='idea'?'개인 분석':'연결된 기록')}</span><h1>${esc(r.title)}</h1><p>${esc(r.channel||'')} · ${esc(r.date||'')}</p>${r.oneLiner?`<div class="hero">${esc(r.oneLiner)}</div>`:''}<div class="plain">${esc(r.body||r.summary||'')}</div>${r.userJudgment&&r.userJudgment!==r.body?`<h2>사용자 판단</h2><div class="plain">${esc(r.userJudgment)}</div>`:''}<h2>연결된 근거</h2>${(r.researchEvidence||[]).map(e=>`<div class="evidence"><p>${esc(e.text)}</p>${link(e.sourceUrl,'원자료')}</div>`).join('')}<p>${link(r.link,'출처')}</p>${r.kind==='idea'?`<button data-edit="${esc(r.id)}">이 분석 수정</button>`:''}${r.researchHistory?.length?`<details><summary>이전 기록 ${r.researchHistory.length}개</summary>${r.researchHistory.slice().reverse().map(h=>`<div class="source"><p>${koreanTime(h.at)} 이전 내용</p><div class="plain">${esc(h.body)}</div></div>`).join('')}</details>`:''}`;}
function capture(){root.querySelectorAll('.page').forEach(p=>{scrolls.set(p.dataset.id,p.querySelector('.pagebody').scrollTop);});}
function render(){if(!data)return;capture();const visible=visiblePages(state,window.innerWidth);nav.innerHTML=`<div class="row">${state.pages.map((id,i)=>`<button data-select="${esc(id)}" aria-pressed="${state.active===id}">${i+1} ${esc(title(id))}${visible.includes(id)?'':' · 접힘'}</button>`).join('')}</div>${state.full?'<button class="primary" data-action="restore">← 이전 배치로 돌아가기</button>':`<span>${state.pages.length}개 열림 · ${visible.length}개 표시</span>`}`;root.dataset.count=visible.length;root.innerHTML=visible.map(id=>`<section class="page ${id==='note'?'note':''} ${state.full?'full':''}" data-id="${esc(id)}" aria-label="${esc(title(id))}"><div class="pagebar"><span>${esc(title(id))}</span><div class="row">${state.full?'<button data-action="restore">← 돌아가기</button>':`<button data-full="${esc(id)}" aria-label="${esc(title(id))} 전체 페이지">전체 페이지</button>`}${id!=='summary'&&!state.full?`<button data-close="${esc(id)}" aria-label="${esc(title(id))} 닫기">닫기</button>`:''}</div></div><div class="pagebody">${({summary,cpi,release,note,collection}[id]||(()=>recordPage(id)))()}</div></section>`).join('');drawChart();root.querySelectorAll('.page').forEach(p=>p.querySelector('.pagebody').scrollTop=scrolls.get(p.dataset.id)||0);persist();}
function drawChart(){const host=$('.chart');if(!host)return;const w=host.clientWidth,h=235,l=58,r=14,t=22,b=44;const a=data.points.map(p=>p[state.series]),lo=Math.min(...a),hi=Math.max(...a),pad=Math.max((hi-lo)*.18,.05),x=i=>l+i*(w-l-r)/(a.length-1),y=v=>t+(hi+pad-v)/(hi-lo+2*pad)*(h-t-b);const labels=w<350?[0,2,4,6]:a.map((_,i)=>i);host.innerHTML=`<svg width="${w}" height="${h}" role="img" aria-label="${esc(data.series[state.series].title)} 계절조정 전월 대비 월별 상승률"><rect x="${l}" y="${t}" width="${w-l-r}" height="${h-t-b}" fill="none" stroke="var(--line)"/>${[lo,(lo+hi)/2,hi].map(v=>`<text x="${l-8}" y="${y(v)+5}" text-anchor="end">${Number(v.toFixed(2))}</text>`).join('')}<polyline fill="none" stroke="var(--green)" stroke-width="2.5" points="${a.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}"/>${a.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="${i===state.month?5:3}" fill="var(--green)"><title>${data.points[i].period}: ${v}%</title></circle>`).join('')}${labels.filter(i=>i<a.length).map(i=>`<text x="${x(i)}" y="${h-23}" text-anchor="${i===0?'start':i===a.length-1?'end':'middle'}">${Number(data.points[i].period.slice(5))}월</text>`).join('')}<text x="${l}" y="16">%</text><text x="${w-r}" y="${h-2}" text-anchor="end">2026년</text></svg>`;}
async function save(){if(busy||!repo)return;if(!draft.dirty&&draft.expected){saveStatus="변경한 내용이 없습니다.";render();return;}let patch;try{patch=buildRecord(draft,data);}catch(e){saveStatus=e.message;render();return;}busy=true;conflict=false;draft.operation ||= uuid();const attempt={...draft,evidence:[...draft.evidence]},operation=draft.operation;persist();render();try{const saved=await repo.save(attempt.id,patch,attempt.expected,operation);draft.expected=recordFingerprint(saved);draft.operation=null;draft.dirty=draft.body!==attempt.body||draft.title!==attempt.title||draft.oneLiner!==attempt.oneLiner||JSON.stringify(draft.evidence)!==JSON.stringify(attempt.evidence);saveStatus=draft.dirty?'앞선 내용을 저장했습니다. 새로 입력한 내용은 초안으로 남아 있습니다.':'기록보관실에 저장했습니다.';if(!records.some(r=>r.id===attempt.id))records.unshift({id:attempt.id,...saved});else records=records.map(r=>r.id===attempt.id?{id:attempt.id,...saved}:r);}catch(e){conflict=e.message==='CONFLICT';saveStatus=conflict?'저장 충돌: 원격 기록을 덮어쓰지 않았습니다.':'저장하지 못했습니다. 초안은 유지됩니다. 연결 후 다시 눌러 주세요.';}finally{busy=false;persist();render();}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;capture();if(b.dataset.open){state=openPage(state,b.dataset.open);render();}else if(b.dataset.full){expand(b.dataset.full);}else if(b.dataset.select){state.active=b.dataset.select;if(state.full)state.full=state.active;render();}else if(b.dataset.close){state=closePage(state,b.dataset.close);render();}else if(b.dataset.series){state.series=b.dataset.series;render();}else if(b.dataset.pin){if(!highlights.includes(b.dataset.pin))highlights.push(b.dataset.pin);render();notice('공식 근거를 왼쪽 핵심에 연결했습니다.');}else if(b.dataset.unpin){highlights=highlights.filter(x=>x!==b.dataset.unpin);render();}else if(b.dataset.view){state.view=b.dataset.view;render();}else if(b.dataset.edit){if(draft.dirty&&draft.id!==b.dataset.edit){notice('작성 중인 초안을 먼저 저장하거나 내려받으세요.');state=openPage(state,'note');render();return;}const r=records.find(x=>x.id===b.dataset.edit);draft={id:r.id,title:r.title||'',oneLiner:r.oneLiner||'',body:r.body||r.userJudgment||'',evidence:(r.researchEvidence||[]).map(x=>x.id),expected:recordFingerprint(r),dirty:false,operation:null};saveStatus='';state=openPage(state,'note');render();}else if(b.dataset.action==='restore'){restore();}else if(b.dataset.action==='save')save();else if(b.dataset.action==='copy'){draft.id=uuid();draft.expected=null;draft.operation=null;draft.dirty=true;save();}else if(b.dataset.action==='new'){if(draft.dirty){notice('현재 초안을 먼저 저장하세요. 초안 내려받기로 별도 보관할 수도 있습니다.');return;}draft=blank();saveStatus='';render();}else if(b.dataset.action==='export'){const blob=new Blob([JSON.stringify({schema:'research-draft/1',draft},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='CPI-분석-초안.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
document.addEventListener('input',e=>{const fields={'draft-title':'title','draft-one':'oneLiner','draft-body':'body'};if(fields[e.target.id]){draft[fields[e.target.id]]=e.target.value;draft.dirty=true;draft.operation=null;persist();const el=$('.save-status');if(el)el.textContent=localError?'초안 보관 실패 · 내려받기로 보관하세요.':'이 브라우저에 초안 보관 중 · 아직 기록보관실에 저장하지 않음';}});
document.addEventListener('change',e=>{if(e.target.id==='month'){state.month=Number(e.target.value);render();}if(e.target.dataset.evidence){const id=e.target.dataset.evidence;draft.evidence=e.target.checked?[...new Set([...draft.evidence,id])]:draft.evidence.filter(x=>x!==id);draft.dirty=true;draft.operation=null;persist();}});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(render,100);});window.addEventListener('pagehide',persist);
$('#version').textContent=RELEASE.version;$('#about').innerHTML=`<p>${esc(RELEASE.summary)}</p><p>버전 시각: ${koreanTime(RELEASE.at)} 서울</p><p><a href="docs/RESEARCH-STANDARD.md" target="_blank">공통 보기 규칙</a> · <a href="docs/RESEARCH-CHANGELOG.md" target="_blank">변경 이력</a></p>`;
try{data=validateData(await fetch('data/research-cpi.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error();return r.json();}));state.series=['all','core'].includes(state.series)?state.series:'all';state.month=Math.min(Math.max(Number(state.month)||0,0),data.points.length-1);$('#about').innerHTML+=`<p>자료 확인: ${koreanTime(data.verifiedAt)} 서울</p><p>${esc(data.updatePolicy)}</p><p>${link(data.sourceUrl,'BLS 원자료')}</p>`;render();notice();}catch{notice('공식 CPI 자료를 불러오지 못했습니다. 새로고침하거나 기존 매크로 화면을 이용해 주세요.');}
let requestedHandled=false;
if(data){try{repo=await connectRecords();cloudStatus='기록보관실 연결됨';notice();render();unwatch=repo.watch(list=>{records=list;const requested=new URLSearchParams(location.search).get('record');if(requested&&!requestedHandled&&records.some(r=>r.id===requested)){state=openPage(state,'record:'+requested);requestedHandled=true;}if(document.activeElement?.matches('input,textarea'))return;render();},()=>{cloudStatus='기록 목록을 불러오지 못했습니다 · 입력은 유지됩니다';notice();});}catch{cloudStatus='기록보관실 연결 실패 · 초안은 이 브라우저에 보관';notice();render();const retry=document.createElement('button');retry.textContent='연결 다시 시도';retry.onclick=()=>{persist();location.reload();};$('#notice').append(' ',retry);}}
