import {safeUrl,koreanDate} from './research-core.mjs';
export const plain=v=>String(v??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
export function articleUrl(value){const safe=safeUrl(value);if(!safe)return '';const u=new URL(safe);for(const k of [...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid)$/i.test(k))u.searchParams.delete(k);u.hash='';return u.href;}
export function publishedTime(value){const raw=String(value||'');if(!/(Z|[+-]\d{2}:?\d{2}|GMT|UTC)\s*$/i.test(raw))return '';const n=Date.parse(raw);return Number.isFinite(n)?new Date(n).toISOString():'';}
export async function newsId(url){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(url));return 'radar-'+[...new Uint8Array(digest)].map(n=>n.toString(16).padStart(2,'0')).join('');}
export async function normalizeRadar(data){const arr=Array.isArray(data)?data:data?.items;if(!Array.isArray(arr))throw Error('뉴스레이더 응답 형식이 올바르지 않습니다.');const urls=new Map();for(const n of arr){const url=articleUrl(n.url||n.link),title=plain(n.title);if(!url||!title)continue;if(urls.has(url)){urls.get(url).duplicates++;continue;}const publishedAt=publishedTime(n.date),sourceName=plain(n.origin)||new URL(url).hostname;urls.set(url,{kind:'news',scope:'radar',title,date:publishedAt?koreanDate(publishedAt):'',publishedAt,publishedRaw:plain(n.date),collectedRaw:plain(n.collected_at),sourceName,sourceUrl:url,summary:plain(n.summary),excerpt:plain(n.body),keyword:plain(n.kw),collector:plain(n.src),topics:[],stocks:[],duplicates:1,raw:{}});}
 const rows=await Promise.all([...urls.values()].map(async n=>{const id=await newsId(n.sourceUrl);return {...n,id,key:'radar:'+id};}));if(arr.length&&!rows.length)throw Error('사용할 수 있는 기사 주소와 제목이 없습니다.');return rows.sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt));}
export function mergeRadar(base,news){const saved=new Map();for(const r of base){if(r.key.startsWith('record:')){const u=articleUrl(r.sourceUrl);if(u)saved.set(u,r);}}return [...base,...news.filter(n=>!saved.has(n.sourceUrl))];}
export function candidates(item,news,keywords=[]){return news.map(n=>{const text=[n.title,n.keyword,n.summary,n.excerpt].join(' ').toLocaleLowerCase();const hits=keywords.filter(k=>{const term=String(k).toLocaleLowerCase();return /^[a-z0-9]+$/.test(term)?new RegExp('(^|[^a-z0-9])'+term+'([^a-z0-9]|$)','i').test(text):text.includes(term);});return {item:n,hits};}).filter(x=>x.hits.length);}
export function newsRecord(n,now=Date.now()){if(n.scope!=='radar'||!articleUrl(n.sourceUrl)||!n.title)throw Error('보관할 뉴스 형식을 확인해 주세요.');return {kind:'news',schemaVer:2,date:n.date,title:n.title,oneLiner:n.summary,body:n.excerpt,channel:n.sourceName,link:n.sourceUrl,source:{name:n.sourceName,url:n.sourceUrl},topics:[],stocks:[],checks:[],star:0,aiInterpretation:'',userJudgment:'',createdAt:now,updatedAt:now,radarArticleId:n.id,radarKeyword:n.keyword,radarCollector:n.collector,radarCollectedRaw:n.collectedRaw,articlePublishedAt:n.publishedAt,articlePublishedRaw:n.publishedRaw,importedFrom:'news-radar',contentLabel:'뉴스레이더 수집 요약·발췌 · 원문 대조 필요'};}
export async function fetchRadar(url,fetcher=fetch){if(!safeUrl(url))throw Error('뉴스 공급 주소를 확인할 수 없습니다.');const response=await fetcher(url,{cache:'no-cache',signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('뉴스 공급 응답 오류 '+response.status);return normalizeRadar(await response.json());}
