import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import {analysisReadiness,missingEvidenceOutput,buildAnalysisPrompt,analysisFingerprint} from '../lib/ai_core.js';
const empty={event_id:'E',versions:[{rcept_no:'20260914800398'}]};
assert.equal(analysisReadiness(empty,null).canAnalyze,false);
assert.equal(analysisReadiness({...empty,facts:{amount:null}},null).canAnalyze,false);
const source={status:'AVAILABLE',rceptNo:'20260914800398',text:'실적 공시 본문 '.repeat(30)};
const e={...empty,sourceDocument:source};
assert.equal(analysisReadiness(e,null).canAnalyze,true);
assert.equal(analysisReadiness({...e,sourceDocument:{...source,rceptNo:'wrong'}},null).canAnalyze,false);
assert.equal(analysisReadiness(e,{statement:'매출 성장'}).hasThesis,true);
assert.notEqual(analysisFingerprint({event:e,model:'x'}),analysisFingerprint({event:empty,model:'x'}));
assert.match(buildAnalysisPrompt(e,null).system,/Korean/);
assert.match(buildAnalysisPrompt(e,null).user,/실적 공시 본문/);
const html=fs.readFileSync(new URL('../../events.html',import.meta.url),'utf8');
const inline=[...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)].map(x=>x[1]).join('\n');
new vm.Script(inline);
const fields=inline.slice(inline.indexOf('const AI_FIELDS='),inline.indexOf('function badge'));
const render=inline.slice(inline.indexOf('function renderAiOutput'),inline.indexOf('async function analyze'));
const renderOutput=vm.runInNewContext(fields+render+';renderAiOutput',{esc:x=>String(x).replaceAll('<','&lt;')});
const output=renderOutput(missingEvidenceOutput(),{thesisAssessment:'INSUFFICIENT_DATA'});
assert.match(output,/판단 불가/);assert.doesNotMatch(output,/POSITIVE_CASE|THESIS_IMPACT/);
assert.match(renderOutput({...missingEvidenceOutput(),factSummary:'<script>alert(1)</script>'}),/&lt;script>/);
console.log('Korean / evidence / UI regressions: PASS');
