import test from 'node:test';import assert from 'node:assert/strict';
import {handleRecordsAI,costNano,parseResult,makeRequest,normalizeSelection,MODEL} from '../backend/records-ai.js';
const sources=[{id:'a',title:'A',text:'수요가 증가했다.'},{id:'b',title:'B',text:'공급은 그대로다.'}];
const output={facts:[{text:'자료의 수요 증가 주장',sourceId:'a',quote:'수요가 증가했다.'}],interpretations:[{text:'공급 압박 가능성',reasoning:'수요와 공급을 함께 비교',sourceIds:['a','b'],counterargument:'자료의 시점이 다를 수 있음'}],conflicts:[],unknowns:['원출처 독립 검증 전'],nextChecks:['발표 시점 확인']};
const reply={id:'resp_test',status:'completed',usage:{input_tokens:1000,input_tokens_details:{cached_tokens:200},output_tokens:100},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(output)}]}]};
function harness(){
 const docs=new Map(sources.map(s=>['records/'+s.id,{title:s.title,body:s.text}]));
 let chain=Promise.resolve();
 const snap=k=>({exists:docs.has(k),data:()=>docs.get(k)});
 const ref=k=>({key:k,get:async()=>snap(k),collection:n=>col(k+'/'+n)});
 const col=k=>({doc:id=>ref(k+'/'+id),where:()=>({get:async()=>({docs:[...docs].filter(([key,v])=>key.startsWith(k+'/')&&v.schema).map(([key,v])=>({id:key.split('/').pop(),data:()=>v}))})})});
 return {docs,db:{collection:col,runTransaction(fn){const p=chain.then(async()=>{const writes=[];await fn({get:async r=>snap(r.key),set:(r,v)=>writes.push([r.key,v])});writes.forEach(([k,v])=>docs.set(k,v));});chain=p.catch(()=>{});return p;}}};
}
test('cost uses exact cache categories, missing usage remains unknown',()=>{assert.equal(costNano(reply.usage),405000);assert.equal(costNano(null),null);assert.equal(costNano({input_tokens:3,output_tokens:1,input_tokens_details:{cached_tokens:4}}),null);});
test('facts must quote stored source; interpretation needs multiple sources',()=>{assert.deepEqual(parseResult(reply,sources),output);const bad=structuredClone(reply);bad.output[0].content[0].text=JSON.stringify({...output,facts:[{text:'추측',sourceId:'a',quote:'없던 문장'}]});assert.throws(()=>parseResult(bad,sources));assert.throws(()=>normalizeSelection({recordIds:['a','a']}));assert.equal(makeRequest(sources,'질문').model,MODEL);});
test('concurrent identical calls charge once; cost survives a different client',async()=>{const h=harness();let calls=0;const args={db:h.db,uid:'owner',input:{action:'records-analyze',recordIds:['a','b']},key:'test',fetchImpl:async()=>{calls++;return {ok:true,json:async()=>reply};}};const result=await Promise.all([handleRecordsAI(args),handleRecordsAI(args)]);assert.equal(calls,1);assert(result.some(x=>x.status==='completed'));const reused=await handleRecordsAI(args);assert.equal(calls,1);assert.equal(reused.cached,true);const cost=await handleRecordsAI({...args,input:{action:'records-costs'}});assert.equal(cost.totals.spentNano,405000);assert.equal(cost.totals.reservedNano,0);assert.equal(cost.billed,null);assert.equal(h.docs.get('records/a').body,sources[0].text);});
test('provider timeout retains reserve and unknown count, never reports free',async()=>{const h=harness();let calls=0;const args={db:h.db,uid:'owner',input:{action:'records-analyze',recordIds:['a','b']},key:'test',fetchImpl:async()=>{calls++;throw Error('timeout');}};await handleRecordsAI(args);await handleRecordsAI(args);assert.equal(calls,1);const cost=await handleRecordsAI({...args,input:{action:'records-costs'}});assert.equal(cost.totals.unknown,1);assert(cost.totals.reservedNano>0);});
test('invalid model output is still charged from response usage',async()=>{const h=harness(),args={db:h.db,uid:'owner',input:{action:'records-analyze',recordIds:['a','b']},key:'test',fetchImpl:async()=>({ok:true,json:async()=>({...reply,status:'incomplete'})})};assert.equal((await handleRecordsAI(args)).status,'failed');assert.equal((await handleRecordsAI({...args,input:{action:'records-costs'}})).totals.spentNano,405000);});
